server:
  port: ${BFF_SERVICE_PORT:8443}

spring:
  main:
    web-application-type: reactive
  application:
    name: BffVyntra
  profiles:
    default: local

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:3600000}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:86400000}
